### ISSUE TITLE
Can you make the test network address of https://api.ston.fi/ public? I need this to try to get the pool.

### ISSUE THREAD

**Issue by whatTheHellDie** [ston-fi/api#2]
Can you make the test network address of https://api.ston.fi/ public? I need this to try to get the pool.

**Comment by pavel-rakhmanov** [comment]
Yep, we will definitely do it in the near future. We are already testing our API internally and plan to open it as soon as possible. I will update the DOCs and provide a testnet version of the STON API when it is ready
